name: matlab

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        matlab: [R2021a, R2023b]

    runs-on: ${{ matrix.os }}

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}

    - uses: actions/checkout@v4

    - name: Run Matlab tests (buildtool)
      if: ${{ matrix.matlab >= 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-build@v2

    - name: Run tests (manual)
      if: ${{ matrix.matlab < 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-tests@v2
      with:
        strict: true
        select-by-folder: test
