name: matlab

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        matlab: ["R2023a"]
        include:
        - os: ubuntu-latest
          matlab: "R2023b"

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.matlab }}

    - uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset default
