name: matlab

env:
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        matlab: [R2021a,R2023a]
        include:
        - os: ubuntu-latest
          matlab: R2023b
# R2023b only available on Linux runner as of Sept 2023

    runs-on: ${{ matrix.os }}

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v1
      with:
        release: ${{ matrix.matlab }}

    - uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset default
